import type { Ticket, Project, TeamMember, TimeEntry } from "./models/models";

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Desarrollo Web",
    key: "DW",
    description: "Proyecto principal de desarrollo web",
    lead: {
      name: "Juan Pérez",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    members: 8,
    tickets: 45,
  },
  {
    id: "2",
    name: "App Móvil",
    key: "AM",
    description: "Aplicación móvil iOS y Android",
    lead: {
      name: "María García",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    members: 6,
    tickets: 32,
  },
  {
    id: "3",
    name: "Backend API",
    key: "BA",
    description: "API REST del sistema",
    lead: {
      name: "Carlos López",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    members: 5,
    tickets: 28,
  },
];

export const mockTickets: Ticket[] = [
  {
    id: "DW-101",
    title: "Implementar sistema de autenticación",
    description: "Crear el sistema de login y registro con JWT",
    type: "feature",
    priority: "high",
    status: "in-progress",
    assignee: {
      name: "Juan Pérez",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "JP",
    },
    reporter: {
      name: "María García",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "MG",
    },
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    dueDate: new Date("2024-02-01"),
    project: "Desarrollo Web",
    labels: ["backend", "security"],
    comments: 5,
    timeTracked: 12,
    timeEstimate: 20,
  },
  {
    id: "DW-102",
    title: "Corregir error en el formulario de contacto",
    description: "Los emails no se están enviando correctamente",
    type: "bug",
    priority: "urgent",
    status: "todo",
    assignee: {
      name: "Carlos López",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "CL",
    },
    reporter: {
      name: "Ana Martínez",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "AM",
    },
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
    dueDate: new Date("2024-01-22"),
    project: "Desarrollo Web",
    labels: ["frontend", "bug"],
    comments: 3,
    timeTracked: 2,
    timeEstimate: 4,
  },
  {
    id: "DW-103",
    title: "Optimizar consultas de base de datos",
    description: "Las consultas están tomando demasiado tiempo",
    type: "improvement",
    priority: "medium",
    status: "in-review",
    assignee: {
      name: "Luis Rodríguez",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "LR",
    },
    reporter: {
      name: "Juan Pérez",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "JP",
    },
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-19"),
    dueDate: new Date("2024-01-25"),
    project: "Desarrollo Web",
    labels: ["backend", "performance"],
    comments: 8,
    timeTracked: 16,
    timeEstimate: 16,
  },
  {
    id: "AM-201",
    title: "Diseñar pantalla de perfil de usuario",
    description: "Crear mockups y wireframes para la pantalla de perfil",
    type: "task",
    priority: "medium",
    status: "backlog",
    assignee: null,
    reporter: {
      name: "María García",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "MG",
    },
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
    dueDate: new Date("2024-02-05"),
    project: "App Móvil",
    labels: ["design", "ui"],
    comments: 1,
    timeTracked: 0,
    timeEstimate: 8,
  },
  {
    id: "AM-202",
    title: "Implementar notificaciones push",
    description: "Configurar Firebase Cloud Messaging para notificaciones",
    type: "feature",
    priority: "high",
    status: "in-progress",
    assignee: {
      name: "Pedro Sánchez",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "PS",
    },
    reporter: {
      name: "María García",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "MG",
    },
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-20"),
    dueDate: new Date("2024-01-28"),
    project: "App Móvil",
    labels: ["mobile", "notifications"],
    comments: 6,
    timeTracked: 10,
    timeEstimate: 15,
  },
  {
    id: "BA-301",
    title: "Crear endpoint para reportes",
    description: "Desarrollar API REST para generación de reportes",
    type: "feature",
    priority: "medium",
    status: "todo",
    assignee: {
      name: "Carlos López",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "CL",
    },
    reporter: {
      name: "Juan Pérez",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "JP",
    },
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
    dueDate: new Date("2024-02-10"),
    project: "Backend API",
    labels: ["api", "backend"],
    comments: 2,
    timeTracked: 0,
    timeEstimate: 12,
  },
  {
    id: "DW-104",
    title: "Actualizar dependencias del proyecto",
    description: "Actualizar todas las librerías a sus últimas versiones",
    type: "task",
    priority: "low",
    status: "done",
    assignee: {
      name: "Ana Martínez",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "AM",
    },
    reporter: {
      name: "Juan Pérez",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "JP",
    },
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-17"),
    dueDate: new Date("2024-01-20"),
    project: "Desarrollo Web",
    labels: ["maintenance"],
    comments: 4,
    timeTracked: 6,
    timeEstimate: 6,
  },
  {
    id: "DW-105",
    title: "Agregar modo oscuro",
    description: "Implementar tema oscuro en toda la aplicación",
    type: "feature",
    priority: "low",
    status: "backlog",
    assignee: null,
    reporter: {
      name: "Luis Rodríguez",
      avatar: "/placeholder.svg?height=32&width=32",
      initials: "LR",
    },
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
    dueDate: null,
    project: "Desarrollo Web",
    labels: ["frontend", "ui"],
    comments: 0,
    timeTracked: 0,
    timeEstimate: 10,
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Juan Pérez",
    email: "juan.perez@company.com",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "JP",
    role: "admin",
    status: "active",
    joinedAt: new Date("2023-01-15"),
    assignedTickets: 12,
    completedTickets: 45,
  },
  {
    id: "2",
    name: "María García",
    email: "maria.garcia@company.com",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "MG",
    role: "manager",
    status: "active",
    joinedAt: new Date("2023-02-20"),
    assignedTickets: 8,
    completedTickets: 38,
  },
  {
    id: "3",
    name: "Carlos López",
    email: "carlos.lopez@company.com",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "CL",
    role: "developer",
    status: "active",
    joinedAt: new Date("2023-03-10"),
    assignedTickets: 15,
    completedTickets: 52,
  },
  {
    id: "4",
    name: "Ana Martínez",
    email: "ana.martinez@company.com",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "AM",
    role: "developer",
    status: "active",
    joinedAt: new Date("2023-04-05"),
    assignedTickets: 10,
    completedTickets: 41,
  },
  {
    id: "5",
    name: "Luis Rodríguez",
    email: "luis.rodriguez@company.com",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "LR",
    role: "designer",
    status: "active",
    joinedAt: new Date("2023-05-12"),
    assignedTickets: 6,
    completedTickets: 28,
  },
  {
    id: "6",
    name: "Pedro Sánchez",
    email: "pedro.sanchez@company.com",
    avatar: "/placeholder.svg?height=32&width=32",
    initials: "PS",
    role: "qa",
    status: "active",
    joinedAt: new Date("2023-06-18"),
    assignedTickets: 9,
    completedTickets: 35,
  },
];

export const mockTimeEntries: TimeEntry[] = [
  {
    id: "1",
    ticketId: "DW-101",
    ticketTitle: "Implementar sistema de autenticación",
    userId: "1",
    userName: "Juan Pérez",
    userAvatar: "/placeholder.svg?height=32&width=32",
    description: "Configuración inicial de JWT y middleware",
    duration: 4.5,
    date: new Date("2024-01-20"),
    startTime: new Date("2024-01-20T09:00:00"),
    endTime: new Date("2024-01-20T13:30:00"),
  },
  {
    id: "2",
    ticketId: "DW-101",
    ticketTitle: "Implementar sistema de autenticación",
    userId: "1",
    userName: "Juan Pérez",
    userAvatar: "/placeholder.svg?height=32&width=32",
    description: "Implementación de endpoints de login y registro",
    duration: 6,
    date: new Date("2024-01-19"),
    startTime: new Date("2024-01-19T09:00:00"),
    endTime: new Date("2024-01-19T15:00:00"),
  },
  {
    id: "3",
    ticketId: "DW-102",
    ticketTitle: "Corregir error en el formulario de contacto",
    userId: "3",
    userName: "Carlos López",
    userAvatar: "/placeholder.svg?height=32&width=32",
    description: "Investigación del problema de envío de emails",
    duration: 2,
    date: new Date("2024-01-20"),
    startTime: new Date("2024-01-20T14:00:00"),
    endTime: new Date("2024-01-20T16:00:00"),
  },
  {
    id: "4",
    ticketId: "AM-202",
    ticketTitle: "Implementar notificaciones push",
    userId: "6",
    userName: "Pedro Sánchez",
    userAvatar: "/placeholder.svg?height=32&width=32",
    description: "Configuración de Firebase Cloud Messaging",
    duration: 5,
    date: new Date("2024-01-20"),
    startTime: new Date("2024-01-20T09:00:00"),
    endTime: new Date("2024-01-20T14:00:00"),
  },
  {
    id: "5",
    ticketId: "DW-103",
    ticketTitle: "Optimizar consultas de base de datos",
    userId: "5",
    userName: "Luis Rodríguez",
    userAvatar: "/placeholder.svg?height=32&width=32",
    description: "Análisis de queries y creación de índices",
    duration: 8,
    date: new Date("2024-01-19"),
    startTime: new Date("2024-01-19T09:00:00"),
    endTime: new Date("2024-01-19T17:00:00"),
  },
];
